remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

exclude:
  - README.md

title: Title Here
tagline: Here is the site's description, as a subtitle.
description: Here is the site's description, for search engines.
